name: RESTful Post Feed Updater

on:
  schedule:
    # Runs 6 hours day
    - cron: '0 */6 * * *'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      
      - name: Install Dependencies
        run: python -m pip install --upgrade pip |
             pip install -r feed_updater/requirements.txt

      - name: Running Updater Script
        run: python feed_updater/updater.py
          
      - name: Add files to staging area
        run: git add .
      - name: Commit changes
        run: git commit -m "Added some changes"
      - name: Push changes
        run: git push
